name: export

on:
  workflow_dispatch:
    inputs:
      solution-name:
        required: true
        default: ALM2Solution
permissions:
  contents: write
  
jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
        
    - name: Install Power Platform tools
      uses: microsoft/powerplatform-actions/actions-install@v1
      
    - name: Run Power Platform WhoAmI 
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
        environment-url: ${{ vars.DEV_ENVIRONMENT_URL }}
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ secrets.TENANT_ID }}

    - name: Export unmanaged solution
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{ vars.DEV_ENVIRONMENT_URL }}
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ secrets.TENANT_ID }}
        solution-name: ${{ github.event.inputs.solution-name }}
        solution-output-file: ${{ github.event.inputs.solution-name }}.zip
        overwrite: true

    - name: Unpack solution
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: ${{ github.event.inputs.solution-name }}.zip
        solution-folder: ${{ github.event.inputs.solution-name }}
        solution-type: 'Unmanaged'
        overwrite-files: true
       
    - name: Export managed solution
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
            environment-url: ${{ vars.DEV_ENVIRONMENT_URL }}
            app-id: ${{ secrets.CLIENT_ID }}
            client-secret: ${{ secrets.CLIENT_SECRET }}
            tenant-id: ${{ secrets.TENANT_ID }}
            solution-name: ${{ github.event.inputs.solution-name }}
            solution-output-file: ${{ github.event.inputs.solution-name }}_managed.zip
            overwrite: true
            managed: true
            
    - name: Commit changes to the repository
      run: |
        git fetch --all  
        git config --global user.email “MattRumaCSA@DemoCSUAppInnovation.onmicrosoft.com”
        git config --global user.name "Automatic.Build"
        git checkout main
        git add --all 
        git commit -m "Updates from the dev environment" --allow-empty
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push
